create table batch_formulas (current_total_weight decimal(14,4) not null, target_batch_size decimal(14,4) not null, created_at datetime(6), id bigint not null auto_increment, project_ref_id bigint not null, updated_at datetime(6), batch_name varchar(255) not null, formula_snapshot TEXT not null, remark TEXT, status varchar(255) not null, primary key (id)) engine=InnoDB;
create table benchmarks (created_at datetime(6), id bigint not null auto_increment, updated_at datetime(6), benchmark_id varchar(255), claimed_benefits TEXT, competitor_name varchar(255) not null, ingredients_list TEXT, product_name varchar(255) not null, project_id varchar(255), segment varchar(255), status varchar(255) not null, primary key (id)) engine=InnoDB;
create table business_sequences (current_value bigint not null, sequence_name varchar(80) not null, primary key (sequence_name)) engine=InnoDB;
create table calibration_records (date date not null, created_at datetime(6), equipment_id bigint not null, id bigint not null auto_increment, updated_at datetime(6), note varchar(1000), done_by varchar(255), instrument_type varchar(255) not null, machine_id varchar(255) not null, readings json, status varchar(255) not null, primary key (id)) engine=InnoDB;
create table dossiers (created_at datetime(6), id bigint not null auto_increment, project_ref_id bigint not null, updated_at datetime(6), status varchar(24) not null, checklist_json TEXT, mfr_snapshot_json TEXT, primary key (id)) engine=InnoDB;
create table equipment (last_calibration date, next_calibration date, created_at datetime(6), id bigint not null auto_increment, updated_at datetime(6), frequency varchar(255), instrument_type varchar(255) not null, machine_id varchar(255) not null, model varchar(255), name varchar(255) not null, serial_number varchar(255), status varchar(255), calibration_template json, primary key (id)) engine=InnoDB;
create table ingredients (specific_gravity decimal(10,6), created_at datetime(6), id bigint not null auto_increment, updated_at datetime(6), cas_number varchar(255), compliance_status varchar(255), ec_no varchar(255), erp_code varchar(255) not null, grade varchar(255), inci_name varchar(255) not null, ingredient_function varchar(255), price varchar(255), safety_level varchar(255), supplier_name varchar(255) not null, trade_name varchar(255) not null, uom varchar(255), primary key (id)) engine=InnoDB;
create table procedure_files (created_at datetime(6), id bigint not null auto_increment, project_ref_id bigint not null, protocol_ref_id bigint not null, updated_at datetime(6), batch_no varchar(120), batch_size varchar(120), date_of_completion varchar(120), document_no varchar(120), mfg_date varchar(120), mfr_no varchar(120), mixer_capacity varchar(120), revision_date varchar(120), revision_no varchar(120), shelf_life varchar(120), brand_name varchar(255), product_name varchar(255), primary key (id)) engine=InnoDB;
create table procedure_rows (row_order integer not null, created_at datetime(6), id bigint not null auto_increment, section_ref_id bigint not null, updated_at datetime(6), actual_qty varchar(120), formula_qty_per_100_kg varchar(120), rpm varchar(120), standard_time varchar(120), name_of_material TEXT, primary key (id)) engine=InnoDB;
create table procedure_sections (step_no integer not null, created_at datetime(6), id bigint not null auto_increment, procedure_file_ref_id bigint not null, updated_at datetime(6), description_of_process TEXT, primary key (id)) engine=InnoDB;
create table project_documents (file_size bigint not null, id bigint not null auto_increment, project_ref_id bigint not null, uploaded_at datetime(6), content_type varchar(255) not null, original_file_name varchar(255) not null, stored_file_name varchar(255) not null, uploaded_by varchar(255) not null, primary key (id)) engine=InnoDB;
create table projects (trial_cycle integer not null, created_at datetime(6), id bigint not null auto_increment, updated_at datetime(6), lifecycle_stage varchar(40) not null, benchmark_id varchar(255) not null, project_id varchar(255) not null, project_name varchar(255), status varchar(255) not null, primary key (id)) engine=InnoDB;
create table roles (id bigint not null auto_increment, name varchar(20), primary key (id)) engine=InnoDB;
create table stability_gate_criteria (max_ph_drift decimal(10,4), max_weight_loss_percent decimal(10,4), created_at datetime(6), id bigint not null auto_increment, project_ref_id bigint not null, updated_at datetime(6), condition_thresholds_json TEXT, mandatory_parameters_json TEXT, primary key (id)) engine=InnoDB;
create table stability_gate_decisions (batch_ref_id bigint not null, created_at datetime(6), decided_at datetime(6), generated_batch_ref_id bigint, id bigint not null auto_increment, project_ref_id bigint not null, protocol_ref_id bigint not null, outcome varchar(12) not null, rca_category varchar(64), decided_by varchar(120), decision_reason TEXT, measured_values_json TEXT, mfr_snapshot_json TEXT, rca_corrective_action TEXT, rca_failure_note TEXT, rule_checks_json TEXT, suspected_ingredients_json TEXT, primary key (id)) engine=InnoDB;
create table stability_observations (current_weight decimal(14,4), initial_weight decimal(14,4), observed_on date, created_at datetime(6), id bigint not null auto_increment, protocol_ref_id bigint not null, result_status varchar(8) not null, updated_at datetime(6), condition_label varchar(120) not null, interval_label varchar(120) not null, measurements_json TEXT not null, note TEXT, primary key (id)) engine=InnoDB;
create table stability_protocols (batch_formula_ref_id bigint not null, created_at datetime(6), id bigint not null auto_increment, project_ref_id bigint not null, updated_at datetime(6), status varchar(24) not null, protocol_name varchar(160) not null, conditions_json TEXT not null, intervals_json TEXT not null, master_formula_info_json TEXT, parameter_references_json TEXT, parameters_json TEXT not null, primary key (id)) engine=InnoDB;
create table user_roles (role_id bigint not null, user_id bigint not null, primary key (role_id, user_id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(255) not null, page_access_csv TEXT, password varchar(255), username varchar(255) not null, primary key (id)) engine=InnoDB;
create index idx_batch_formulas_project on batch_formulas (project_ref_id);
create index idx_batch_formulas_status on batch_formulas (status);
alter table batch_formulas add constraint uk_batch_formulas_batch_name unique (batch_name);
create index idx_benchmarks_status on benchmarks (status);
alter table benchmarks add constraint UK7976j6tha0kd0apselsi2hj92 unique (benchmark_id);
alter table benchmarks add constraint UKs2ns76cghygvd81hdfjlmcc6n unique (project_id);
alter table dossiers add constraint UKd4rypugvq9dgkoxxn28yemks unique (project_ref_id);
alter table equipment add constraint UKon7579ldb2ce05ep7e5oumyyt unique (machine_id);
alter table ingredients add constraint UKlxcl3u20u02t1x4q6034qno5d unique (erp_code);
create index idx_procedure_files_project on procedure_files (project_ref_id);
create index idx_procedure_files_protocol on procedure_files (protocol_ref_id);
alter table procedure_files add constraint uk_procedure_files_protocol unique (protocol_ref_id);
create index idx_procedure_rows_section on procedure_rows (section_ref_id);
alter table procedure_rows add constraint uk_procedure_rows_section_order unique (section_ref_id, row_order);
create index idx_procedure_sections_file on procedure_sections (procedure_file_ref_id);
create index idx_procedure_sections_step_no on procedure_sections (step_no);
create index idx_project_documents_project on project_documents (project_ref_id);
create index idx_project_documents_uploaded_at on project_documents (uploaded_at);
alter table project_documents add constraint UKagfx399k6brhfvbiyc0h77urr unique (stored_file_name);
create index idx_projects_status on projects (status);
create index idx_projects_lifecycle_stage on projects (lifecycle_stage);
alter table projects add constraint UKldt712fajuavigvvwfbok6nc1 unique (benchmark_id);
alter table projects add constraint UKr4sng6mj7mni8wyteu3g52kbr unique (project_id);
alter table roles add constraint UKofx66keruapi6vyqpv6f2or37 unique (name);
alter table stability_gate_criteria add constraint UKs5gy74q7ica6dvtgu3wohteat unique (project_ref_id);
create index idx_stability_observations_protocol on stability_observations (protocol_ref_id);
create index idx_stability_observations_observed_on on stability_observations (observed_on);
alter table stability_observations add constraint uk_stability_observations_protocol_condition_interval unique (protocol_ref_id, condition_label, interval_label);
create index idx_stability_protocols_project on stability_protocols (project_ref_id);
create index idx_stability_protocols_batch_formula on stability_protocols (batch_formula_ref_id);
create index idx_stability_protocols_status on stability_protocols (status);
alter table users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table project_documents add constraint FKtng40qdj4mqikcu9pdv6soodf foreign key (project_ref_id) references projects (id);
alter table user_roles add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 foreign key (role_id) references roles (id);
alter table user_roles add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references users (id);
